[package]
name = "libsodium-sys"
version = "0.1.0"
authors = ["Y. T. Chung <zonyitoo@gmail.com>"]
links = "sodium"
build = "build.rs"
license = "MIT/ISC"
repository = "https://github.com/zonyitoo/sodium-rs"
description = "Native bindings to the libsodium library"

[lib]
name = "libsodium_sys"

[build-dependencies]
pkg-config = "*"
