[package]
name = "libsodium-ffi"
version = "0.1.4"
authors = ["Y. T. Chung <zonyitoo@gmail.com>"]
links = "sodium"
build = "build.rs"
license = "MIT/ISC"
repository = "https://github.com/zonyitoo/sodium-rs"
description = "Native bindings (FFI) to the libsodium library"

[lib]
name = "libsodium_ffi"

[build-dependencies]
pkg-config = "0.3"

[dependencies]
libc = "0.2"
